baseURL = "https://davidbuck.net/"
title = "David Buck"
languageCode = "en-us"
disableKinds = ["taxonomy", "taxonomyTerm"]
pygmentsStyle= "manni"

[[menu.main]]
identifier = "about"
name       = "About"
url        = "/about/"
weight     = 2

[[menu.main]]
identifier = "posts"
name       = "Posts"
url        = "/post/"
weight     = 1

[outputs]
home = [ "RSS", "HTML"]
section  = ["HTML"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"


[params]
  footerText = "David Buck — Front-End Developer"
  twitterUser = "david_buck"
  githubUser = "davidbuck"
